version: '3.8'
services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      GID: "${GID-1000}"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik"
    volumes:
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./db:/var/lib/crowdsec/data/
      - ./config:/etc/crowdsec/
      - .././logs:/var/log/traefik/:ro
      - ./init.sh:/etc/crowdsec/init.sh
      - ./bouncer_api_key:/etc/crowdsec/bouncer_api_key  # Para compartir la clave    
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    entrypoint: ["bash", "/etc/crowdsec/init.sh"] 

  bouncer-traefik:
    image: docker.io/fbonalair/traefik-crowdsec-bouncer:latest
    container_name: bouncer-traefik
    environment:
      CROWDSEC_BOUNCER_API_KEY: "${BOUNCER_API_KEY}"
      CROWDSEC_AGENT_HOST: crowdsec:8080
    volumes:
      - ./bouncer_api_key:/etc/crowdsec/bouncer_api_key:ro
      - ./entry.sh:/etc/crowdsec/entry.sh
    networks:
      - proxy
    depends_on:
      - crowdsec
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    entrypoint: ["bash", "/usr/local/bin/entry.sh"]

networks:
  proxy:
    external: true