services:
  db:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${SERVICE}
      MYSQL_USER: ${SERVICE}
      MYSQL_PASSWORD: ${PASSWORD}

  wordpress:
    image: wordpress:latest    
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${SERVICE}
      WORDPRESS_DB_PASSWORD: ${PASSWORD}
    ports:
      - 1447:80    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${URL_SERVICIO}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"
    networks:
      - proxy

volumes:
  mysql:


networks:
  default:
  proxy:
    external: true
