services:
  mysql:
    image: mariadb:lts
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${SERVICE}
      MYSQL_USER: ${SERVICE}
      MYSQL_PASSWORD: ${PASSWORD}    
    expose:
      - 3306
    networks:
      - default

  wordpress:
    image: wordpress:latest    
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${SERVICE}
      WORDPRESS_DB_USER: ${SERVICE}
      WORDPRESS_DB_PASSWORD: ${PASSWORD}
    volumes:
      - wordpress:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${URL_SERVICIO}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=myresolver"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"
    networks:
      - proxy
      - default

volumes:
  mysql:
  wordpress:

networks:
  default:
  proxy:
    external: true
